# Running Docker Containers
# $ docker compose up
#
version: "3.9"

# ==============================================================================
# Extensions: Base config for a node
#
# Since docker swarm assumes replicas are identically configured nodes as part
# of a homogenous cluster, we instead opted to declare nodes independently so
# we can configure them slightly differently, with different block database
# files and miner profiles. We can still DRY up our configuration here by
# declaring a base node here to have others merge with.
#
x-node-config: &node
  image: golang:1.21
  command: |
    bash -c "make up"
  volumes:
    - ../../:/source
    - .:/scripts
  working_dir: /source

services:

  node-1:
    <<: *node
    container_name: blockchain-node-1
    environment:
      NODE_STATE_ORIGIN_PEERS: "blockchain-node-1:9080"
      NODE_STATE_BENEFICIARY: miner1
      NODE_STATE_CONSENSUS: POA
      NODE_WEB_PUBLIC_HOST: blockchain-node-1:8080
      NODE_WEB_PRIVATE_HOST: blockchain-node-1:9080
       # Use ephemeral filesystem on container for the node.
      NODE_STATE_DB_PATH: /blocks/
    ports:
      - 7080:7080
      - 8080:8080
      - 9080:9080

  node-2:
    <<: *node
    container_name: blockchain-node-2
    command: |
      bash -c "/scripts/wait-for-master-node.sh make up"
    environment:
      NODE_STATE_ORIGIN_PEERS: "blockchain-node-1:9080"
      NODE_STATE_BENEFICIARY: miner2
      NODE_STATE_CONSENSUS: POA
      NODE_WEB_PUBLIC_HOST: blockchain-node-2:8280
      NODE_WEB_PRIVATE_HOST: blockchain-node-2:9280
      # Use ephemeral filesystem on container for node.
      NODE_STATE_DB_PATH: /blocks/
    ports:
      - 8280:8280
      - 9280:9280

  node-3:
    <<: *node
    container_name: blockchain-node-3
    command: |
      bash -c "/scripts/wait-for-master-node.sh make up"
    environment:
      NODE_STATE_ORIGIN_PEERS: "blockchain-node-1:9080"
      NODE_STATE_BENEFICIARY: miner3
      NODE_STATE_CONSENSUS: POA
      NODE_WEB_PUBLIC_HOST: blockchain-node-3:8380
      NODE_WEB_PRIVATE_HOST: blockchain-node-3:9380
      # Use ephemeral filesystem on container for node.
      NODE_STATE_DB_PATH: /blocks/
    ports:
      - 8380:8380
      - 9380:9380

  #viewer:
  #  image: golang:1.21
  #  command: "go run app/services/viewer/main.go | go run app/tooling/logfmt/main.go"
  #  volumes:
  #  - .:/source
  #  working_dir: /source
  #  ports:
  #    - 80:80